on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin

      - run: ./gradlew clean build

      - uses: actions/upload-artifact@v3
        with:
          name: intellij-jump
          if-no-files-found: error
          path: build/distributions/intellij-jump-*.zip

  prerelease:
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    concurrency:
      group: prerelease
      cancel-in-progress: true

    steps:
      - uses: actions/download-artifact@v3
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: prerelease
          prerelease: true
          title: HEAD
          files: |
            intellij-jump/*

  release:
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v3
      - uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            intellij-jump/*
